# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-31 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_timestamp', models.DateTimeField()),
                ('tip_text', models.CharField(max_length=200)),
                ('tip_link', models.CharField(max_length=100)),
                ('tip_author', models.CharField(max_length=20)),
                ('tip_published', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='tip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythontips.Tip'),
        ),
    ]
