# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-31 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pythontips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='tip_count',
        ),
        migrations.AddField(
            model_name='link',
            name='link',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
