# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-01 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythontips', '0003_auto_20190731_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='tip_link',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tip',
            name='tip_published',
            field=models.BooleanField(default=True),
        ),
    ]
